# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'SelabInventoryHelper' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SelabInventoryHelper
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'FirebaseFirestoreSwift', '> 7.0-beta'

  target 'SelabInventoryHelperTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SelabInventoryHelperUITests' do
    # Pods for testing
  end

end
